# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 11:57
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('lifetime_unit', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'minutes'), (1, 'hours'), (2, 'days'), (3, 'months'), (4, 'Stop every year'), (5, 'NonStop')], default=0, null=True)),
                ('stop_type', models.PositiveSmallIntegerField(choices=[(0, 'Date/Time'), (1, 'Period')], default=0)),
                ('start_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('stop_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=46)),
                ('build_date', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecificDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifetime_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('lifetime_unit', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'minutes'), (1, 'hours'), (2, 'days'), (3, 'months'), (4, 'Stop every year'), (5, 'NonStop')], default=0, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('stop_datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('month_json', django.contrib.postgres.fields.jsonb.JSONField()),
                ('days_json', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=512)),
                ('country', models.CharField(max_length=46)),
                ('birthDate', models.DateField(default=datetime.datetime.today, verbose_name='Date')),
                ('weight_kg', models.PositiveSmallIntegerField(default=1)),
                ('blood', models.CharField(choices=[('A', 'A-type'), ('B', 'B-type'), ('AB', 'AB-type'), ('O', 'O-type')], max_length=2)),
                ('height_cm', models.SmallIntegerField(default=1)),
                ('primary_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prim_school', to='hopes.School')),
                ('secondary_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_school', to='hopes.School')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
